name: wzx ClientWorker Config
hotcofig:
    - https://cdn.jsdelivr.net/gh/website-pages/blog@main/config.yaml
    - https://fastly.jsdelivr.net/gh/website-pages/blog@main/config.yaml
cleaninterval: 1000*60*5
#! Client Worker语法糖
catch_rules:
  - rule: _
    transform_rules:
      - search: _
        action: fetch
        fetch:
          engine: fetch 
          preflight: false
          timeout: 5000
          cache:
            expire: 1000*60*60*12
  #! 并发CDN流量请求 - npm
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|testingcf|quantil)\.jsdelivr\.net\/npm|unpkg\.com)
    transform_rules:
      - search: _
        replace:
          - _
          - https://cdn.jsdelivr.net/npm
          - https://unpkg.com
          - https://unpkg.zhimg.com        #? 回源已关闭，原缓存有效
          - https://npm.elemecdn.com       #? 2022/7/12 确认关闭回源，缓存有效
          # - https://code.bdstatic.com/npm  #? 确认关闭回源，缓存有效
          - https://npm.sourcegcdn.com     #? 滥用封仓库，强制数字版本号
          - https://cdn.bilicdn.tk/npm     #? 由GamerNoTitle提供的反代，请勿滥用:D
          - https://npm.onmicrosoft.cn     #? zkeq大佬反代，请征得cdn主人同意后使用
          - https://unpkg.onmicrosoft.cn   #? zkeq大佬反代，请征得cdn主人同意后使用
          - https://jsd.onmicrosoft.cn/npm #? zkeq大佬反代，请征得cdn主人同意后使用
          - https://cdn1.tianli0.top/npm   #? Tianli大佬反代，请征得cdn主人同意后使用
          - https://jsd.8b9.cn/npm         #? 捌比玖大佬反代，请征得cdn主人同意后使用
        action: fetch 
        fetch:
          engine: parallel
          preflight: false
          timeout: 5000
          cache:
            expire: 1000*60*60*12
  #! 并发CDN流量请求 - GitHub
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|testingcf|quantil)\.jsdelivr\.net\/gh)
    transform_rules:
      - search: _
        replace:
          - _
          - https://cdn.jsdelivr.net/gh
          - https://cdn.bilicdn.tk/gh     #? 由GamerNoTitle提供的反代，请勿滥用:D
          - https://jsd.onmicrosoft.cn/gh #? zkeq大佬反代，请征得cdn主人同意后使用
          - https://cdn1.tianli0.top/gh   #? Tianli大佬反代，请征得cdn主人同意后使用
          - https://jsd.8b9.cn/gh         #? 捌比玖大佬反代，请征得cdn主人同意后使用
        action: fetch
        fetch:
          engine: parallel
          preflight: false
          timeout: 5000
          cache:
            expire: 1000*60*60*12
  #! 并发CDN流量请求 - CDNJS
  - rule: ^https\:\/\/cdnjs\.cloudflare\.com\/ajax\/libs
    transform_rules:
      - search: _
        replace:
          - _
          - https://cdn.bootcdn.net/ajax/libs
          - https://lib.baomitu.com
          - https://mirrors.cqupt.edu.cn/cdnjs/ajax/libs    #? 重庆邮电
          - https://cdn.staticfile.org
          - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs  #? 南大
          - https://cdnjs.sourcegcdn.com/ajax/libs          #? 全同步 https://cdnjs.cloudflare.com
        action: fetch
        fetch:
          engine: parallel
          preflight: false
          timeout: 5000
          cache:
            expire: 1000*60*60*12
  - rule: ^http\:\/\/
    transform_rules:
      - search: ^http\:\/\/
        replace: ^https\:\/\/
        action: fetch
        fetch:
          engine: fetch
          preflight: false
          timeout: 5000
  - rule: ^https\:\/\/hm\.baidu\.com\/hm\.gif
    transform_rules:
      - search: ^https\:\/\/hm\.baidu\.com\/hm\.gif
        action: return

#! 3.0.0-beta-2新增：默认skip
#  - rule: .*
#    transform_rules:
#      - search: .*
#        action: skip   #? 2.8.1新增：跳过cw规则
#! 以下部分会造成报错，已移除
#  - rule: .*
#    transform_rules:
#      - search: .*
#        action: fetch
#        fetch:
#          engine: fetch
#          preflight: false
#          timeout: 5000
#          expire: 1000*60*60*12
#      - search: (^4|^5)
#        searchin: status
#        action: return
#        return:
#          body: ERROR!
#          status: 503
